//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInquiryApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Student
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int ZipCode { get; set; }
        public int Phone { get; set; }
        public string Email { get; set; }
        public string College { get; set; }
        public IEnumerable<SelectListItem> Colleges { get; set; }
        public string Interest { get; set; }
    }
}
